name: Send Webhook

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request
        run: |
          curl -X POST https://webhook.site/a72752d1-10cf-4363-bdec-e0341f576244 \
          -H "Content-Type: application/json" \
          -d '{"message": "Hello from GitHub Actions!"}'
